# Generated by Django 3.2.8 on 2022-01-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_alter_destination_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
